// <auto-generated />
namespace TVS.Ef.Migration.Declaration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddTablesDeclarationSuspension : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTablesDeclarationSuspension));
        
        string IMigrationMetadata.Id
        {
            get { return "201703151024364_AddTablesDeclarationSuspension"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
