// <auto-generated />
namespace TVS.Ef.Migration.Declaration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ajoutchampA12018contributionsocialesolidarite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajoutchampA12018contributionsocialesolidarite));
        
        string IMigrationMetadata.Id
        {
            get { return "201903021114435_ajoutchampA12018contributionsocialesolidarite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
