//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVS.Module.Employee.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TVS.Module.Employee.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nature de l’identifiant.
        /// </summary>
        internal static string _07 {
            get {
                return ResourceManager.GetString("07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant bénéficiaire.
        /// </summary>
        internal static string _08 {
            get {
                return ResourceManager.GetString("08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom et prénom ou raison sociale.
        /// </summary>
        internal static string _09 {
            get {
                return ResourceManager.GetString("09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernière adresse du bénéficiaire.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a1 {
            get {
                object obj = ResourceManager.GetObject("a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro d’ordre.
        /// </summary>
        internal static string A106 {
            get {
                return ResourceManager.GetString("A106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Situation familiale du bénéficiaire.
        /// </summary>
        internal static string A112 {
            get {
                return ResourceManager.GetString("A112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre d’enfants à charge.
        /// </summary>
        internal static string A113 {
            get {
                return ResourceManager.GetString("A113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date début de la période de travail.
        /// </summary>
        internal static string A114 {
            get {
                return ResourceManager.GetString("A114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date fin de la période de travail.
        /// </summary>
        internal static string A115 {
            get {
                return ResourceManager.GetString("A115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée de la période en nombre de jours.
        /// </summary>
        internal static string A116 {
            get {
                return ResourceManager.GetString("A116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenu imposable.
        /// </summary>
        internal static string A117 {
            get {
                return ResourceManager.GetString("A117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valeur des avantages en nature.
        /// </summary>
        internal static string A118 {
            get {
                return ResourceManager.GetString("A118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total du revenu brut imposable.
        /// </summary>
        internal static string A119 {
            get {
                return ResourceManager.GetString("A119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenu réinvesti.
        /// </summary>
        internal static string A120 {
            get {
                return ResourceManager.GetString("A120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des retenues opérées selon le régime commun.
        /// </summary>
        internal static string A121 {
            get {
                return ResourceManager.GetString("A121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des retenues opérées au taux de 20%.
        /// </summary>
        internal static string A122 {
            get {
                return ResourceManager.GetString("A122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant net servi.
        /// </summary>
        internal static string A123 {
            get {
                return ResourceManager.GetString("A123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des traitements et salaires prélevés au titre de la contribution conjoncturelle..
        /// </summary>
        internal static string A124 {
            get {
                return ResourceManager.GetString("A124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retenue 1 % [2015].
        /// </summary>
        internal static string A198 {
            get {
                return ResourceManager.GetString("A198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contribution conjoncturelle [2014].
        /// </summary>
        internal static string A199 {
            get {
                return ResourceManager.GetString("A199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a2 {
            get {
                object obj = ResourceManager.GetObject("a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Salaire non imposable.
        /// </summary>
        internal static string A200 {
            get {
                return ResourceManager.GetString("A200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La contribution sociale de solidarité due sur les traitements, salaires, rémunérations, indemnités[2018].
        /// </summary>
        internal static string A201 {
            get {
                return ResourceManager.GetString("A201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type des montants servis au titre des honoraires, commissions,
        ///courtages, loyers, rémunérations payées en contre partie de la performance dans la prestation, et rémunérations des activités non commerciales servis à des personnes résidentes et établies..
        /// </summary>
        internal static string A212 {
            get {
                return ResourceManager.GetString("A212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Montant brut des honoraires, commissions, courtages, loyers, rémunérations payées en contre partie de la performance dans la prestation et rémunérations des activités non commerciales servis à des personnes résidentes et établies..
        /// </summary>
        internal static string A213 {
            get {
                return ResourceManager.GetString("A213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le  Montant  brut  des  honoraires, commissions, courtages,  loyers  et rémunérations  des  activités  non
        ///commerciales.
        /// </summary>
        internal static string A2131 {
            get {
                return ResourceManager.GetString("A2131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les commissions  des  distributeurs agrées  des  opérateurs téléphoniques..
        /// </summary>
        internal static string A2132 {
            get {
                return ResourceManager.GetString("A2132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honoraires servis aux sociétés et aux personnes physiques soumises au régime réel.
        /// </summary>
        internal static string A214 {
            get {
                return ResourceManager.GetString("A214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jetons de présence, et actions et parts sociales..
        /// </summary>
        internal static string A215 {
            get {
                return ResourceManager.GetString("A215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jetons de présence..
        /// </summary>
        internal static string A2151 {
            get {
                return ResourceManager.GetString("A2151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions et parts sociales..
        /// </summary>
        internal static string A2152 {
            get {
                return ResourceManager.GetString("A2152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rémunérations payées aux salariés et aux non salariés en contrepartie d’un travail occasionnel ou accidentel en dehors de leur activité principale.
        /// </summary>
        internal static string A216 {
            get {
                return ResourceManager.GetString("A216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus-value immobilière (prix de l’immeuble déclaré dans l’acte).
        /// </summary>
        internal static string A217 {
            get {
                return ResourceManager.GetString("A217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loyers des Hôtels payés aux sociétés et aux personnes physiques soumises au régime réel.
        /// </summary>
        internal static string A218 {
            get {
                return ResourceManager.GetString("A218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rémunérations servies aux artistes et créateurs.
        /// </summary>
        internal static string A219 {
            get {
                return ResourceManager.GetString("A219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Honoraires servis aux bureaux d’études exportateurs.
        /// </summary>
        internal static string A220 {
            get {
                return ResourceManager.GetString("A220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type des montants servis au titre des honoraires, commissions, courtages, loyers et rémunérations des activités non commerciales provenant des opérations d’exportation..
        /// </summary>
        internal static string A221 {
            get {
                return ResourceManager.GetString("A221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Montant brut des honoraires, commissions, courtages, loyers et rémunérations des activités non commerciales provenant des opérations d’exportation..
        /// </summary>
        internal static string A222 {
            get {
                return ResourceManager.GetString("A222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des retenues opérées.
        /// </summary>
        internal static string A223 {
            get {
                return ResourceManager.GetString("A223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant net servi.
        /// </summary>
        internal static string A224 {
            get {
                return ResourceManager.GetString("A224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a3 {
            get {
                object obj = ResourceManager.GetObject("a3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intérêts des comptes spéciaux d’épargne ouverts auprès des banques et de la CENT.
        /// </summary>
        internal static string A312 {
            get {
                return ResourceManager.GetString("A312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intérêts des autres capitaux mobiliers.
        /// </summary>
        internal static string A313 {
            get {
                return ResourceManager.GetString("A313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intérêts des prêts payés aux établissements bancaires non établis en Tunisie.
        /// </summary>
        internal static string A314 {
            get {
                return ResourceManager.GetString("A314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des retenues opérées.
        /// </summary>
        internal static string A315 {
            get {
                return ResourceManager.GetString("A315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant net servi.
        /// </summary>
        internal static string A316 {
            get {
                return ResourceManager.GetString("A316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a4 {
            get {
                object obj = ResourceManager.GetObject("a4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type des Montants servis au titre des honoraires, commissions, courtages, loyers, rémunérations des activités non commerciales et autres revenus.
        /// </summary>
        internal static string A412 {
            get {
                return ResourceManager.GetString("A412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taux des Montants servis au titre des honoraires, commissions,
        ///montants servis aux non résidents établis en Tunisie et qui ne
        ///procèdent pas au dépôt de la déclaration d’existence, ....
        /// </summary>
        internal static string A413 {
            get {
                return ResourceManager.GetString("A413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant brut servi au titre des honoraires, commissions,
        ///montants servis aux non résidents établis en Tunisie et qui ne
        ///procèdent pas au dépôt de la déclaration d’existence, ....
        /// </summary>
        internal static string A414 {
            get {
                return ResourceManager.GetString("A414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taux des honoraires servis aux personnes non résidentes qui réalisent des travaux de construction ou des opérations de montage ou des services de contrôles connexes ou d’autres services pour une période ne dépassant pas 6 mois..
        /// </summary>
        internal static string A415 {
            get {
                return ResourceManager.GetString("A415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des honoraires servis aux personnes non résidentes qui réalisent des travaux de construction ou des opérations de montage ou des services de contrôles connexes ou d’autres services pour une période ne dépassant pas 6 mois..
        /// </summary>
        internal static string A416 {
            get {
                return ResourceManager.GetString("A416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taux de plus-value immobilière..
        /// </summary>
        internal static string A417 {
            get {
                return ResourceManager.GetString("A417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant de la plus-value immobilière..
        /// </summary>
        internal static string A418 {
            get {
                return ResourceManager.GetString("A418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taux de plus-value de cession des actions, des parts sociales ou des parts de fonds prévues par la législation.
        /// </summary>
        internal static string A419 {
            get {
                return ResourceManager.GetString("A419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant plus-value de cession des actions, des parts sociales ou des parts de fonds prévues par la législation.
        /// </summary>
        internal static string A420 {
            get {
                return ResourceManager.GetString("A420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenus des valeurs mobilières..
        /// </summary>
        internal static string A4201 {
            get {
                return ResourceManager.GetString("A4201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jetons de présence..
        /// </summary>
        internal static string A4202 {
            get {
                return ResourceManager.GetString("A4202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions et parts sociales..
        /// </summary>
        internal static string A4203 {
            get {
                return ResourceManager.GetString("A4203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taux de revenues des valeurs
        ///mobilières y compris jetons de présence, actions et parts sociales..
        /// </summary>
        internal static string A421 {
            get {
                return ResourceManager.GetString("A421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des revenues des valeurs mobilières y compris jetons de présence, actions et parts sociales.
        /// </summary>
        internal static string A422 {
            get {
                return ResourceManager.GetString("A422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant  des  revenus  de  valeurs.
        /// </summary>
        internal static string A4221 {
            get {
                return ResourceManager.GetString("A4221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jetons de Présence.
        /// </summary>
        internal static string A4222 {
            get {
                return ResourceManager.GetString("A4222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions et parts sociales.
        /// </summary>
        internal static string A4223 {
            get {
                return ResourceManager.GetString("A4223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type des montants servis au titre des honoraires, commissions,
        ///courtages, loyers et rémunérations des activités non commerciales provenant des opérations d’exportation..
        /// </summary>
        internal static string A423 {
            get {
                return ResourceManager.GetString("A423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le montant brut des honoraires, commissions, courtages, loyers et rémunérations des activités non commerciales provenant des opérations d’exportation..
        /// </summary>
        internal static string A424 {
            get {
                return ResourceManager.GetString("A424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le montant des rémunérations ou revenus servis à des personnes résidentes ou établies dans un Etat ou un territoire dont le régime fiscal est privilégié.
        /// </summary>
        internal static string A425 {
            get {
                return ResourceManager.GetString("A425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des retenues opérées .
        /// </summary>
        internal static string A426 {
            get {
                return ResourceManager.GetString("A426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant net servi.
        /// </summary>
        internal static string A427 {
            get {
                return ResourceManager.GetString("A427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a5 {
            get {
                object obj = ResourceManager.GetObject("a5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total des montants égaux ou supérieurs à 1000D y compris la TVA provenant des ventes des entreprises bénéficiant de la déduction des deux tiers des revenus et des ventes des sociétés soumises à l&apos;impôt sur les sociétés aux taux de 10%.
        /// </summary>
        internal static string A512 {
            get {
                return ResourceManager.GetString("A512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total des retenues sur les montants égaux ou supérieurs à 1000D y compris la TVA provenant des ventes des entreprises bénéficiant de la déduction des deux tiers des revenus et des ventes des sociétés soumises à l&apos;impôt sur les sociétés aux taux de 10% .
        /// </summary>
        internal static string A513 {
            get {
                return ResourceManager.GetString("A513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montants égaux ou supérieurs à 1000D y compris la TVA payés au titre des autres opérations.
        /// </summary>
        internal static string A514 {
            get {
                return ResourceManager.GetString("A514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retenue sur les montants égaux ou supérieurs à 1000D y compris la TVA payés au titre des autres opérations.
        /// </summary>
        internal static string A515 {
            get {
                return ResourceManager.GetString("A515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montants égaux ou supérieurs à 1000D y compris la TVA, payés par les entreprises et les établissements publics, et soumis à la retenue à la source au titre de la TVA..
        /// </summary>
        internal static string A516 {
            get {
                return ResourceManager.GetString("A516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retenues sur la TVA au titre des Montants égaux ou supérieurs à 1000D y compris la TVA, payés par les entreprises et les établissements publics et soumis à la retenue à la source au titre de la TVA..
        /// </summary>
        internal static string A517 {
            get {
                return ResourceManager.GetString("A517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montants servis au titre des opérations réalisées avec les personnes n’ayant pas d’établissement en Tunisie et dont la retenue à la source au titre de la TVA est de 100%.
        /// </summary>
        internal static string A518 {
            get {
                return ResourceManager.GetString("A518", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retenues opérées sur les montants servis au titre des opérations réalisées avec les personnes n’ayant pas d’établissement en Tunisie et dont la retenue à la source au titre de la TVA est de 100%.
        /// </summary>
        internal static string A519 {
            get {
                return ResourceManager.GetString("A519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant net servi.
        /// </summary>
        internal static string A520 {
            get {
                return ResourceManager.GetString("A520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a6 {
            get {
                object obj = ResourceManager.GetObject("a6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montants des ristournes commerciales et non commerciales servies..
        /// </summary>
        internal static string A612 {
            get {
                return ResourceManager.GetString("A612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des ventes aux P.P soumises à l’impôt sur le revenu selon le régime forfaitaire..
        /// </summary>
        internal static string A613 {
            get {
                return ResourceManager.GetString("A613", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant de l’avance due sur les ventes aux P.P soumises à l’impôt sur le revenu selon le régime forfaitaire.
        /// </summary>
        internal static string A614 {
            get {
                return ResourceManager.GetString("A614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des revenus au titre des jeux de pari de hasard et de loterie.
        /// </summary>
        internal static string A615 {
            get {
                return ResourceManager.GetString("A615", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retenue à la source au titre des revenus au titre des jeux de pari de hasard et de loterie..
        /// </summary>
        internal static string A616 {
            get {
                return ResourceManager.GetString("A616", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant des ventes des entreprises industrielles et de de commerce au profit des intervenants dans la
        ///distribution de biens et de produits et services qui ne dépassent pas 20.000 DT par an..
        /// </summary>
        internal static string A617 {
            get {
                return ResourceManager.GetString("A617", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retenus à la source sur les ventes des entreprises industrielles et de commerce au profit des intervenants dans la distribution de biens et de produits et services qui ne dépassent pas 20.000 DT par an..
        /// </summary>
        internal static string A618 {
            get {
                return ResourceManager.GetString("A618", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montants perçus en espèces au titre des marchandises vendues et services rendus.
        /// </summary>
        internal static string A619 {
            get {
                return ResourceManager.GetString("A619", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a7 {
            get {
                object obj = ResourceManager.GetObject("a7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type des montants payés.
        /// </summary>
        internal static string A712 {
            get {
                return ResourceManager.GetString("A712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montants payés.
        /// </summary>
        internal static string A713 {
            get {
                return ResourceManager.GetString("A713", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retenue à la source.
        /// </summary>
        internal static string A714 {
            get {
                return ResourceManager.GetString("A714", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant net servi.
        /// </summary>
        internal static string A715 {
            get {
                return ResourceManager.GetString("A715", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_16x16 {
            get {
                object obj = ResourceManager.GetObject("add_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_32x32 {
            get {
                object obj = ResourceManager.GetObject("add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addchartpane_16x16 {
            get {
                object obj = ResourceManager.GetObject("addchartpane_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addchartpane_32x32 {
            get {
                object obj = ResourceManager.GetObject("addchartpane_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addgroupfooter_16x16 {
            get {
                object obj = ResourceManager.GetObject("addgroupfooter_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addgroupfooter_16x161 {
            get {
                object obj = ResourceManager.GetObject("addgroupfooter_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap additem_16x16 {
            get {
                object obj = ResourceManager.GetObject("additem_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Annexe1 {
            get {
                object obj = ResourceManager.GetObject("Annexe1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Annexe2 {
            get {
                object obj = ResourceManager.GetObject("Annexe2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Annexe3 {
            get {
                object obj = ResourceManager.GetObject("Annexe3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Annexe4 {
            get {
                object obj = ResourceManager.GetObject("Annexe4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Annexe5 {
            get {
                object obj = ResourceManager.GetObject("Annexe5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Annexe6 {
            get {
                object obj = ResourceManager.GetObject("Annexe6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Annexe7 {
            get {
                object obj = ResourceManager.GetObject("Annexe7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apply_16x16 {
            get {
                object obj = ResourceManager.GetObject("apply_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apply_32x32 {
            get {
                object obj = ResourceManager.GetObject("apply_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ar {
            get {
                object obj = ResourceManager.GetObject("ar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Archiv {
            get {
                object obj = ResourceManager.GetObject("Archiv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap archiver {
            get {
                object obj = ResourceManager.GetObject("archiver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BC {
            get {
                object obj = ResourceManager.GetObject("BC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bocontact2_16x16 {
            get {
                object obj = ResourceManager.GetObject("bocontact2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bocontact2_32x32 {
            get {
                object obj = ResourceManager.GetObject("bocontact2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendrier {
            get {
                object obj = ResourceManager.GetObject("calendrier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_16x16 {
            get {
                object obj = ResourceManager.GetObject("cancel_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_32x32 {
            get {
                object obj = ResourceManager.GetObject("cancel_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Chef Famille.
        /// </summary>
        internal static string ChefFamille {
            get {
                return ResourceManager.GetString("ChefFamille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_16x16 {
            get {
                object obj = ResourceManager.GetObject("close_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_32x32 {
            get {
                object obj = ResourceManager.GetObject("close_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cnss {
            get {
                object obj = ResourceManager.GetObject("cnss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap colorlegend_16x16 {
            get {
                object obj = ResourceManager.GetObject("colorlegend_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap colorlegend_32x32 {
            get {
                object obj = ResourceManager.GetObject("colorlegend_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_16x16 {
            get {
                object obj = ResourceManager.GetObject("delete_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteheader_16x16 {
            get {
                object obj = ResourceManager.GetObject("deleteheader_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteheader_32x32 {
            get {
                object obj = ResourceManager.GetObject("deleteheader_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deletelist_16x16 {
            get {
                object obj = ResourceManager.GetObject("deletelist_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deletelist_32x32 {
            get {
                object obj = ResourceManager.GetObject("deletelist_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_16x16 {
            get {
                object obj = ResourceManager.GetObject("download_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_32x32 {
            get {
                object obj = ResourceManager.GetObject("download_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier l&apos;activite du bénéficiaire!.
        /// </summary>
        internal static string errBeneficiaireActivite {
            get {
                return ResourceManager.GetString("errBeneficiaireActivite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier l&apos;adresse du bénéficiaire!.
        /// </summary>
        internal static string errBeneficiaireAdresse {
            get {
                return ResourceManager.GetString("errBeneficiaireAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier le type d&apos;identifiant du bénéficiaire!.
        /// </summary>
        internal static string errBeneficiaireType {
            get {
                return ResourceManager.GetString("errBeneficiaireType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier le type d&apos;identifiant du bénéficiaire!.
        /// </summary>
        internal static string errBeneficiereIdent {
            get {
                return ResourceManager.GetString("errBeneficiereIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier le nom du bénéficiaire!.
        /// </summary>
        internal static string errBeneficiereNom {
            get {
                return ResourceManager.GetString("errBeneficiereNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant invalide [{0}]!.
        /// </summary>
        internal static string errMontantInvalid {
            get {
                return ResourceManager.GetString("errMontantInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier le type du montant servis! [{0}].
        /// </summary>
        internal static string errTypeMontantServi {
            get {
                return ResourceManager.GetString("errTypeMontantServi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exporttocsv_16x16 {
            get {
                object obj = ResourceManager.GetObject("exporttocsv_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exporttotxt_16x16 {
            get {
                object obj = ResourceManager.GetObject("exporttotxt_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exporttotxt_32x32 {
            get {
                object obj = ResourceManager.GetObject("exporttotxt_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exporttoxls_16x16 {
            get {
                object obj = ResourceManager.GetObject("exporttoxls_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exporttoxls_32x32 {
            get {
                object obj = ResourceManager.GetObject("exporttoxls_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exporttoxlsx_16x16 {
            get {
                object obj = ResourceManager.GetObject("exporttoxlsx_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exporttoxlsx_32x32 {
            get {
                object obj = ResourceManager.GetObject("exporttoxlsx_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FC {
            get {
                object obj = ResourceManager.GetObject("FC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap financial_16x16 {
            get {
                object obj = ResourceManager.GetObject("financial_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap financial_32x32 {
            get {
                object obj = ResourceManager.GetObject("financial_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grid_16x16 {
            get {
                object obj = ResourceManager.GetObject("grid_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grid_32x32 {
            get {
                object obj = ResourceManager.GetObject("grid_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Inbox_32x32 {
            get {
                object obj = ResourceManager.GetObject("Inbox_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intere Detectible.
        /// </summary>
        internal static string IntereDetectible {
            get {
                return ResourceManager.GetString("IntereDetectible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nouveau {
            get {
                object obj = ResourceManager.GetObject("Nouveau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste_16x16 {
            get {
                object obj = ResourceManager.GetObject("paste_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste_32x32 {
            get {
                object obj = ResourceManager.GetObject("paste_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preview_16x16 {
            get {
                object obj = ResourceManager.GetObject("preview_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preview_32x32 {
            get {
                object obj = ResourceManager.GetObject("preview_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print_16x16 {
            get {
                object obj = ResourceManager.GetObject("print_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print_32x32 {
            get {
                object obj = ResourceManager.GetObject("print_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printquick_16x16 {
            get {
                object obj = ResourceManager.GetObject("printquick_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printquick_32x32 {
            get {
                object obj = ResourceManager.GetObject("printquick_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rec {
            get {
                object obj = ResourceManager.GetObject("rec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_16x16 {
            get {
                object obj = ResourceManager.GetObject("save_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_32x32 {
            get {
                object obj = ResourceManager.GetObject("save_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Supprimer {
            get {
                object obj = ResourceManager.GetObject("Supprimer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tableofcontent_32x32 {
            get {
                object obj = ResourceManager.GetObject("tableofcontent_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap valid {
            get {
                object obj = ResourceManager.GetObject("valid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
